### ISSUE TITLE
下载报错

### ISSUE THREAD

**Issue by ruyizi** [guange2015/down1688#1]
Error handling response: TypeError: Cannot read property 'farewell' of undefined

上下文
_generated_background_page.html
堆叠追踪

background.js:68 (匿名函数)

function genericOnClick2(info){
    console.log('genericOnClick');
    chrome.tabs.query(
      {active: true, currentWindow: true},
      function(tabs) {
            chrome.tabs.sendMessage(
              tabs[0].id,
              {greeting: "hello"},
              function(response) {
                      console.log(response.farewell);
                      downloadFile(response.farewell.shows);
          });
    });
  }

**Comment by guange2015** [comment]
有个地方我没写清楚，需要进到1688的商品详情页再用这个功能发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi  <notifications@github.com>发送时间: 2020年10月25日 17:10收件人: guange2015/down1688 <down1688@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[guange2015/down1688] 下载报错 (#1)
Error handling response: TypeError: Cannot read property 'farewell' of undefined
上下文
_generated_background_page.html
堆叠追踪
background.js:68 (匿名函数)
function genericOnClick2(info){
console.log('genericOnClick');
chrome.tabs.query(
{active: true, currentWindow: true},
function(tabs) {
chrome.tabs.sendMessage(
tabs[0].id,
{greeting: "hello"},
function(response) {
console.log(response.farewell);
downloadFile(response.farewell.shows);
});
});
}

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/guange2015/down1688/issues/1",
"url": "https://github.com/guange2015/down1688/issues/1",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruyizi** [comment]
> 有个地方我没写清楚，需要进到1688的商品详情页再用这个功能发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi <notifications@github.com>发送时间: 2020年10月25日 17:10收件人: guange2015/down1688 <down1688@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[guange2015/down1688] 下载报错 (#1) Error handling response: TypeError: Cannot read property 'farewell' of undefined 上下文 _generated_background_page.html 堆叠追踪 background.js:68 (匿名函数) function genericOnClick2(info){ console.log('genericOnClick'); chrome.tabs.query( {active: true, currentWindow: true}, function(tabs) { chrome.tabs.sendMessage( tabs[0].id, {greeting: "hello"}, function(response) { console.log(response.farewell); downloadFile(response.farewell.shows); }); }); } —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#1", "url": "#1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

就是在1688的详情页面，有的详情没问题，有的就会报错。
https://detail.1688.com/offer/552506967461.html?spm=a2615.7691456.autotrace-offerGeneral.4.705952cdHfT1xG
这个详情页就不能下载

**Comment by guange2015** [comment]
你更新一下最新的版本发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi  <notifications@github.com>发送时间: 2020年10月27日 17:30收件人: guange2015/down1688 <down1688@noreply.github.com>抄送: guange <8863824@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[guange2015/down1688] 下载报错 (#1)

有个地方我没写清楚，需要进到1688的商品详情页再用这个功能发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi notifications@github.com发送时间: 2020年10月25日 17:10收件人: guange2015/down1688 down1688@noreply.github.com抄送: Subscribed subscribed@noreply.github.com主题: 回复：[guange2015/down1688] 下载报错 (#1) Error handling response: TypeError: Cannot read property 'farewell' of undefined 上下文 _generated_background_page.html 堆叠追踪 background.js:68 (匿名函数) function genericOnClick2(info){ console.log('genericOnClick'); chrome.tabs.query( {active: true, currentWindow: true}, function(tabs) { chrome.tabs.sendMessage( tabs[0].id, {greeting: "hello"}, function(response) { console.log(response.farewell); downloadFile(response.farewell.shows); }); }); } —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#1", "url": "#1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

就是在1688的详情页面，有的详情没问题，有的就会报错。
https://detail.1688.com/offer/552506967461.html?spm=a2615.7691456.autotrace-offerGeneral.4.705952cdHfT1xG
这个详情页就不能下载

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/guange2015/down1688/issues/1#issuecomment-717108816",
"url": "https://github.com/guange2015/down1688/issues/1#issuecomment-717108816",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ruyizi** [comment]
> 你更新一下最新的版本发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi <notifications@github.com>发送时间: 2020年10月27日 17:30收件人: guange2015/down1688 <down1688@noreply.github.com>抄送: guange <8863824@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[guange2015/down1688] 下载报错 (#1) 有个地方我没写清楚，需要进到1688的商品详情页再用这个功能发自我的iPhone------------------ 原始邮件 ------------------发件人: ruyizi notifications@github.com发送时间: 2020年10月25日 17:10收件人: guange2015/down1688 down1688@noreply.github.com抄送: Subscribed subscribed@noreply.github.com主题: 回复：[guange2015/down1688] 下载报错 (#1) Error handling response: TypeError: Cannot read property 'farewell' of undefined 上下文 _generated_background_page.html 堆叠追踪 background.js:68 (匿名函数) function genericOnClick2(info){ console.log('genericOnClick'); chrome.tabs.query( {active: true, currentWindow: true}, function(tabs) { chrome.tabs.sendMessage( tabs[0].id, {greeting: "hello"}, function(response) { console.log(response.farewell); downloadFile(response.farewell.shows); }); }); } —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "#1", "url": "#1", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ] 就是在1688的详情页面，有的详情没问题，有的就会报错。 https://detail.1688.com/offer/552506967461.html?spm=a2615.7691456.autotrace-offerGeneral.4.705952cdHfT1xG 这个详情页就不能下载 —You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#1 (comment)](https://github.com/guange2015/down1688/issues/1#issuecomment-717108816)", "url": "[#1 (comment)](https://github.com/guange2015/down1688/issues/1#issuecomment-717108816)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

![image](https://user-images.githubusercontent.com/7381400/97384748-4ea98800-190b-11eb-878a-3d6ec27df683.png)
已更新到最新版本，下载还是报错，是我姿势不对吗？
https://detail.1688.com/offer/552506967461.html?spm=a2615.7691456.autotrace-offerGeneral.4.705952cdHfT1xG

**Comment by guange2015** [comment]
这个是视频的，处理不健壮，更新最新的版本可以了。

**Comment by ruyizi** [comment]
> 这个是视频的，处理不健壮，更新最新的版本可以了。

👌，可以了，奥利给
